# Generated by Django 3.1.5 on 2023-10-15 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(db_column='id', help_text='主键ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', db_index=True, help_text='名称', max_length=64, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, help_text='创建时间', null=True)),
                ('created_by', models.CharField(db_column='created_by', default='sys', help_text='创建者', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='更新时间')),
                ('updated_by', models.CharField(db_column='updated_by', default='sys', help_text='更新者', max_length=32, null=True)),
                ('source', models.CharField(help_text='数据源类型，es,sls,cls,...', max_length=32)),
                ('host', models.CharField(blank=True, help_text='es地址', max_length=128, null=True)),
                ('username', models.CharField(blank=True, help_text='es用户名', max_length=128, null=True)),
                ('password', models.CharField(blank=True, help_text='es密码', max_length=128, null=True)),
                ('project_name', models.CharField(blank=True, help_text='项目名称', max_length=128, null=True)),
                ('logstore', models.CharField(blank=True, help_text='仓库名', max_length=128, null=True)),
                ('region', models.CharField(blank=True, help_text='区域', max_length=128, null=True)),
                ('alisecret', models.CharField(blank=True, help_text='密钥', max_length=128, null=True)),
                ('alikey', models.CharField(blank=True, help_text='KEY', max_length=128, null=True)),
            ],
            options={
                'verbose_name': '数据源信息',
                'verbose_name_plural': '数据源信息',
                'db_table': 'l_datasource',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GateConfig',
            fields=[
                ('id', models.AutoField(db_column='id', help_text='主键ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', db_index=True, help_text='名称', max_length=64, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, help_text='创建时间', null=True)),
                ('created_by', models.CharField(db_column='created_by', default='sys', help_text='创建者', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='更新时间')),
                ('updated_by', models.CharField(db_column='updated_by', default='sys', help_text='更新者', max_length=32, null=True)),
                ('domain', models.CharField(help_text='域名', max_length=128)),
                ('component', models.CharField(blank=True, help_text='组件', max_length=32, null=True)),
                ('datasource_id', models.IntegerField(help_text='数据源id')),
                ('isblack', models.CharField(default='n', help_text='isblack', max_length=4)),
            ],
            options={
                'verbose_name': '网关日志',
                'verbose_name_plural': '网关日志',
                'db_table': 'l_gateconfig',
                'managed': True,
            },
        ),
    ]
