# Generated by Django 3.1.5 on 2023-10-15 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('om_logsearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(db_column='id', help_text='主键ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', db_index=True, help_text='名称', max_length=64, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, help_text='创建时间', null=True)),
                ('created_by', models.CharField(db_column='created_by', default='sys', help_text='创建者', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='更新时间')),
                ('updated_by', models.CharField(db_column='updated_by', default='sys', help_text='更新者', max_length=32, null=True)),
                ('app', models.CharField(help_text='服务名', max_length=64)),
                ('component', models.CharField(blank=True, help_text='组件', max_length=32, null=True)),
                ('datasource_id', models.IntegerField(help_text='数据源id')),
                ('isblack', models.CharField(default='n', help_text='isblack', max_length=4)),
            ],
            options={
                'verbose_name': '服务日志',
                'verbose_name_plural': '服务日志',
                'db_table': 'l_appconfig',
                'managed': True,
            },
        ),
    ]
