# Generated by Django 3.1.5 on 2023-10-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_logsearch', '0002_appconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='name',
            field=models.CharField(db_column='name', help_text='名称', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(db_column='name', help_text='名称', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='gateconfig',
            name='name',
            field=models.CharField(db_column='name', help_text='名称', max_length=64, null=True),
        ),
    ]
