# Generated by Django 3.1.5 on 2023-10-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('om_logsearch', '0003_auto_20231016_1411'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appconfig',
            unique_together={('app', 'component', 'datasource_id')},
        ),
        migrations.AlterUniqueTogether(
            name='gateconfig',
            unique_together={('domain', 'component', 'datasource_id')},
        ),
    ]
