# Generated by Django 3.1.5 on 2023-10-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_logsearch', '0005_componentindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentindex',
            name='field_type',
            field=models.CharField(blank=True, help_text='字段类型', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='componentindex',
            name='time_field',
            field=models.CharField(blank=True, help_text='时间字段', max_length=16, null=True),
        ),
    ]
