# Generated by Django 3.1.5 on 2023-10-17 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('om_logsearch', '0006_auto_20231017_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentindex',
            name='created_at',
            field=models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, help_text='创建时间', null=True),
        ),
        migrations.AddField(
            model_name='componentindex',
            name='created_by',
            field=models.CharField(db_column='created_by', default='sys', help_text='创建者', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='componentindex',
            name='name',
            field=models.CharField(db_column='name', help_text='名称', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='componentindex',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', help_text='更新时间'),
        ),
        migrations.AddField(
            model_name='componentindex',
            name='updated_by',
            field=models.CharField(db_column='updated_by', default='sys', help_text='更新者', max_length=32, null=True),
        ),
    ]
