# Generated by Django 3.1.5 on 2023-10-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('om_logsearch', '0008_auto_20231018_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apppass',
            old_name='node',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='gatepass',
            old_name='node',
            new_name='note',
        ),
    ]
