# Generated by Django 3.1.5 on 2023-10-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_logsearch', '0009_auto_20231018_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentindex',
            name='component',
            field=models.CharField(default='aops-nginx', help_text='组件', max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='componentindex',
            unique_together=set(),
        ),
    ]
