# Generated by Django 3.1.5 on 2023-10-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_logsearch', '0010_auto_20231020_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentindex',
            name='component',
            field=models.CharField(blank=True, help_text='组件', max_length=32, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='componentindex',
            unique_together={('datasource_id', 'component')},
        ),
    ]
