version: "2.2"

services:
  es01:
    image: elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es02,es03
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms6g -Xmx6g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    mem_limit: 10g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s" ]
      interval: 30s
      timeout: 10s
      retries: 5

  es02:
    depends_on:
      - es01
    image: elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      
      - esdata02:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    environment:
      - node.name=es02
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - discovery.seed_hosts=es01,es03
      - ES_JAVA_OPTS=-Xms6g -Xmx6g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    mem_limit: 10g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s" ]
      interval: 30s
      timeout: 10s
      retries: 5

  es03:
    depends_on:
      - es02
    image: elasticsearch:${STACK_VERSION}
    restart: always
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    environment:
      - node.name=es03
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - discovery.seed_hosts=es01,es02
      - ES_JAVA_OPTS=-Xms6g -Xmx6g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    mem_limit: 10g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s" ]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
    image: kibana:${STACK_VERSION}
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    mem_limit: 10g
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
  kibanadata:
    driver: local