# Generated by Django 3.1.5 on 2023-11-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_alarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmidentity',
            name='record_ignore',
            field=models.BooleanField(default=True, help_text='忽略时候是否记录数据到es'),
        ),
    ]
