# Generated by Django 3.1.5 on 2023-11-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_alarm', '0002_alarmidentity_record_ignore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmconfig',
            name='alarm_to',
            field=models.JSONField(blank=True, default={'ding': [], 'email': [], 'phone': [], 'sms': [], 'wechat': []}, null=True),
        ),
    ]
