# Generated by Django 3.1.5 on 2023-11-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_alarm', '0003_auto_20231116_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmconfig',
            name='alert_end',
            field=models.CharField(blank=True, help_text='一天内告警结束时间21:00', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='alarmconfig',
            name='alert_start',
            field=models.CharField(blank=True, help_text='一天内告警开始时间08:00', max_length=8, null=True),
        ),
    ]
