# Generated by Django 3.1.5 on 2023-11-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_alarm', '0004_auto_20231120_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmidentity',
            name='identity',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='alarmidentity',
            name='status',
            field=models.IntegerField(choices=[('0', '消除'), ('1', '正在处理'), ('2', '处理完成'), ('3', '暂时忽略'), ('4', '未处理'), ('5', '自动恢复')], default='4', help_text='状态'),
        ),
    ]
