# Generated by Django 3.1.5 on 2023-11-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_alarm', '0005_auto_20231121_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmidentity',
            name='recover_cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
