# Generated by Django 3.1.5 on 2023-11-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_alarm', '0006_alarmidentity_recover_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmBlack',
            fields=[
                ('id', models.AutoField(db_column='id', help_text='主键ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='创建时间')),
                ('created_by', models.CharField(db_column='created_by', default='sys', help_text='创建者', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='更新时间')),
                ('updated_by', models.CharField(db_column='updated_by', default='sys', help_text='更新者', max_length=32, null=True)),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('rule_re', models.CharField(blank=True, help_text='从summary中取出', max_length=64)),
                ('black_to', models.DateTimeField(blank=True, help_text='截至时间', null=True)),
                ('desc', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'alarm_black',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CacheRead',
            fields=[
                ('id', models.AutoField(db_column='id', help_text='主键ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='创建时间')),
                ('created_by', models.CharField(db_column='created_by', default='sys', help_text='创建者', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='更新时间')),
                ('updated_by', models.CharField(db_column='updated_by', default='sys', help_text='更新者', max_length=32, null=True)),
                ('datatype', models.CharField(db_column='datatype', help_text='datatype', max_length=128, null=True)),
                ('cachestr', models.TextField(blank=True, db_column='cachestr', help_text='cachestr', null=True)),
                ('note', models.CharField(blank=True, db_column='note', help_text='note', max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'cache',
                'verbose_name_plural': 'cache',
                'db_table': 'alarm_cacheread',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='alarmrule',
            name='resovle_freq',
            field=models.CharField(blank=True, help_text='恢复告警频率', max_length=32, null=True),
        ),
    ]
