# Generated by Django 3.1.5 on 2023-12-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_alarm', '0007_auto_20231129_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmcomment',
            name='operator',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
