# Generated by Django 3.1.5 on 2023-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_alarm', '0008_alarmcomment_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmZongjie',
            fields=[
                ('id', models.AutoField(db_column='id', help_text='主键ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', help_text='创建时间')),
                ('created_by', models.CharField(db_column='created_by', default='sys', help_text='创建者', max_length=32, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', help_text='更新时间')),
                ('updated_by', models.CharField(db_column='updated_by', default='sys', help_text='更新者', max_length=32, null=True)),
                ('reach', models.CharField(blank=True, max_length=1500, null=True)),
                ('reason', models.CharField(blank=True, max_length=1500, null=True)),
                ('solution', models.CharField(blank=True, max_length=1500, null=True)),
                ('identity_id', models.IntegerField(db_index=True, help_text='指纹ID')),
            ],
            options={
                'db_table': 'alarm_zongjie',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='AlarmSolution',
        ),
    ]
