# Generated by Django 3.1.5 on 2024-05-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_alarm', '0009_auto_20231204_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmconfig',
            name='label_name',
            field=models.CharField(db_column='label_name', default='source', help_text='分类lable', max_length=16),
        ),
        migrations.AddField(
            model_name='alarmconfig',
            name='label_send',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='alarmconfig',
            name='send_type',
            field=models.CharField(db_column='send_type', default='common', help_text='发送规则', max_length=16),
        ),
    ]
