# Generated by Django 3.1.5 on 2024-05-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('om_alarm', '0010_auto_20240531_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmconfig',
            name='label_send',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
