version: "2.2"
services:
  master:
    image: mysql:8.0.30
    container_name: mysql-master
    ports:
      - "3307:3306"
    volumes:
      - /data/dockerMysql/master/my.cnf:/etc/my.cnf
      - /data/dockerMysql/master/data:/var/lib/mysql
      - /data/dockerMysql/master/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=ops_manage
      - MYSQL_ROOT_PASSWORD=piecelovewudi

  slave:
    image: mysql:8.0.30
    container_name: mysql-slave
    ports:
      - "3308:3306"
    volumes:
      - /data/dockerMysql/slave/my.cnf:/etc/my.cnf
      - /data/dockerMysql/slave/data:/var/lib/mysql
      - /data/dockerMysql/slave/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=ops_manage
      - MYSQL_ROOT_PASSWORD=piecelovewudi
    links:
      - master

