version: "2.2"
services:
  redis-7001:
    image: redis:6
    container_name: redis-7001
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - /etc/redis_cluster/7001/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis_cluster/7001/data:/data
    ports:
      - "7001:7001"
      - "17001:17001"
    environment:
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10'
  redis-7002:
    image: redis:6
    container_name: redis-7002
    command:
      [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - /etc/redis_cluster/7002/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis_cluster/7002/data:/data
    ports:
      - "7002:7002"
      - "17002:17002"
    environment:
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10'
  redis-7003:
    image: redis:6
    container_name: redis-7003
    command:
      [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - /etc/redis_cluster/7003/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis_cluster/7003/data:/data
    ports:
      - "7003:7003"
      - "17003:17003"
    environment:
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10'
  redis-7004:
    image: redis:6
    container_name: redis-7004
    command:
      [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - /etc/redis_cluster/7004/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis_cluster/7004/data:/data
    ports:
      - "7004:7004"
      - "17004:17004"
    environment:
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10'
  redis-7005:
    image: redis:6
    container_name: redis-7005
    command:
      [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - /etc/redis_cluster/7005/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis_cluster/7005/data:/data
    ports:
      - "7005:7005"
      - "17005:17005"
    environment:
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10'
  redis-7006:
    image: redis:6
    container_name: redis-7006
    command:
      [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - /etc/redis_cluster/7006/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis_cluster/7006/data:/data
    ports:
      - "7006:7006"
      - "17006:17006"
    environment:
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10'